//User login//
export const SET_CURRENT_USER='SET_CURRENT_USER';
export const USER_LOGIN_REQUEST='USER_LOGIN_REQUEST';
export const USER_LOGIN_FAIL='USER_LOGIN_FAIL';
export const USER_LOGOUT='USER_LOGOUT';
//    //



//User Register//
export const USER_REGISTER_REQUEST='USER_REGISTER_REQUEST';
export const USER_REGISTER_FAIL='USER_REGISTER_FAIL'